// Generated by gencpp from file serial_pkg/KinematicData.msg
// DO NOT EDIT!


#ifndef SERIAL_PKG_MESSAGE_KINEMATICDATA_H
#define SERIAL_PKG_MESSAGE_KINEMATICDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_pkg
{
template <class ContainerAllocator>
struct KinematicData_
{
  typedef KinematicData_<ContainerAllocator> Type;

  KinematicData_()
    : line_velocity(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  KinematicData_(const ContainerAllocator& _alloc)
    : line_velocity(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _line_velocity_type;
  _line_velocity_type line_velocity;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::serial_pkg::KinematicData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_pkg::KinematicData_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicData_

typedef ::serial_pkg::KinematicData_<std::allocator<void> > KinematicData;

typedef boost::shared_ptr< ::serial_pkg::KinematicData > KinematicDataPtr;
typedef boost::shared_ptr< ::serial_pkg::KinematicData const> KinematicDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_pkg::KinematicData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_pkg::KinematicData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_pkg::KinematicData_<ContainerAllocator1> & lhs, const ::serial_pkg::KinematicData_<ContainerAllocator2> & rhs)
{
  return lhs.line_velocity == rhs.line_velocity &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_pkg::KinematicData_<ContainerAllocator1> & lhs, const ::serial_pkg::KinematicData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_pkg::KinematicData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_pkg::KinematicData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_pkg::KinematicData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_pkg::KinematicData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_pkg::KinematicData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_pkg::KinematicData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_pkg::KinematicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b6ab2dd5908a8a55d4e38931ba25856";
  }

  static const char* value(const ::serial_pkg::KinematicData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b6ab2dd5908a8a5ULL;
  static const uint64_t static_value2 = 0x5d4e38931ba25856ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_pkg::KinematicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_pkg/KinematicData";
  }

  static const char* value(const ::serial_pkg::KinematicData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_pkg::KinematicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 line_velocity\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::serial_pkg::KinematicData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_pkg::KinematicData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line_velocity);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_pkg::KinematicData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_pkg::KinematicData_<ContainerAllocator>& v)
  {
    s << indent << "line_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.line_velocity);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_PKG_MESSAGE_KINEMATICDATA_H
